global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: openmu
    static_configs:
      - targets: ['gameServer1:9464', 'connectServer:9464', 'chatServer:9464']
  