apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: login-state
spec:
  spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-state:6379
  #- name: ttlInSeconds
  #  value: <int> # Optional